### ISSUE TITLE
building error 

### ISSUE THREAD

**Issue by PolGuixe** [studiointeract/accounts-bootstrap#2]
Error: Can't find npm module 'meteor/studiointeract:react-accounts-ui'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?

**Comment by PolGuixe** [comment]
fixed with: 
`import Accounts from 'meteor/std:accounts-ui';`

**Comment by timbrandin** [comment]
@PolGuixe do you believe we need to write something about this in the readme?

**Comment by PolGuixe** [comment]
@timbrandin yes, I've seen that you have already did. ;)

**Comment by timbrandin** [comment]
Cool, I'll close this then.
