### ISSUE TITLE
Don't force type as button, allow links styled as buttons

### ISSUE THREAD

**Issue by todda00** [studiointeract/accounts-bootstrap#3]
This package is forcing the use of buttons instead of links and the forms change state, but not route.

The reason I want to use the router to change the form is for 2 reasons:
1. In the current state, the url path remains the same. For example if you are on the login form /login and then click the register button, the register from is shown, but the user is still at route '/login'.
2. I am adding a headline to the page through a prop setup in the FlowRouter route for each user account page. This also does not change, so it will show Login above the Register form if the user switches to the register from via the button. This is the case for all form states.

**Comment by timbrandin** [comment]
You can easily override the defaults by swapping out the render on the Accounts.ui.Form and Accounts.ui.Button, see how we do that in Semantic or Bootstrap, it's like just a few lines. 👍 

https://github.com/studiointeract/accounts-semantic/blob/master/main.jsx#L70-L98

**Comment by timbrandin** [comment]
But if we find this being the default to use links rather than defaults, a PR changing this would be appropriate and credited in the Readme ;)
