### ISSUE TITLE
atmospherejs's link is dead

### ISSUE THREAD

**Issue by JeremyIglehart** [studiointeract/accounts-bootstrap#4]
## Reproduce this bug:
1. Go to: https://atmospherejs.com/std/accounts-bootstrap
2. Click on "Github" and you go here: https://github.com/std/accounts-bootstrap/

> Suggestion is for you to please change the link to: https://github.com/studiointeract/accounts-bootstrap/

Thank you!

**Comment by timbrandin** [comment]
Thx, updating now.
